apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: off-hours-savings
  namespace: team-alpha-dev
spec:
  weekdays: "1-5"
  sleepAt: "07:00"
  wakeUpAt: "08:00"
  timeZone: "UTC"
  suspendDeployments: true
