apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: off-hours-savings
  namespace: team-alpha-dev
spec:
  weekdays: "*"
  sleepAt: "06:45"
  wakeUpAt: "23:59"
  timeZone: "UTC"
  suspendDeployments: true
