apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: off-hours-savings
  namespace: team-alpha-dev
spec:
  weekdays: "1-5"
  sleepAt: "06:15"
  wakeUpAt: "23:59"
  timeZone: "UTC"
  suspendDeployments: true
